name: refugerecovery
description: Refuge Recovery

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  assets_audio_player: ^1.3.8+1
  video_player: '>=0.10.0 <2.0.0'
  audioplayers: 0.10.1
  webview_flutter:
  get_it:
  url_launcher: ^5.4.2
  webfeed: ^0.4.2
  flutter_html: ^0.11.1
  flutter:
    sdk: flutter
  intl:
  flutter_facebook_login: ^3.0.0
  flutter_markdown: ^0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.2
  google_sign_in: ^4.0.4
  oauth2:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/rr_logo.png
    - assets/google.png
    - assets/google_maps.png
    - assets/facebook.png
    - assets/zoom.jpg
    - assets/www.jpg
    - assets/meditation_audio/loving-kindness.mp3
    - assets/meditation_audio/appreciative-joy.mp3
    - assets/meditation_audio/forgiveness.mp3
    - assets/meditation_audio/equanimity.mp3
    - assets/meditation_audio/compassion.mp3
    - assets/meditation_audio/tonglen.mp3
    - assets/meditation_audio/mindfulness-of-the-breath-and-body.mp3
    - assets/meditation_audio/mindfulness-of-the-feeling-tone.mp3
    - assets/meditation_audio/mindfulness-of-the-feeling-tone-jenna.mp3
    - assets/meditation_audio/mindfulness-of-the-mind-content.mp3
    - assets/meditation_audio/mindfulness-of-the-mind-process.mp3
    - assets/meditation_audio/mindfulness-of-the-truth.mp3
    - assets/meditation_audio/mindfulness-of-breathing.mp3
    - assets/meditation_audio/mindfulness-of-breathing-jenna.mp3
    - assets/meditation_icons/img-metta-meditation-.png
    - assets/meditation_icons/img-appreciation-meditation-.png
    - assets/meditation_icons/img-forgiveness-meditation-.png
    - assets/meditation_icons/img-equinamity-meditation-.png
    - assets/meditation_icons/img-compassion-meditation-.png
    - assets/meditation_icons/img-tonglen-meditation-.png
    - assets/meditation_icons/img-breath-meditation-.png
    - assets/meditation_icons/img-body-meditation-.png
    - assets/meditation_icons/img-mindfulness-meditation-.png
    - assets/meditation_icons/img-process-meditation-.png
    - assets/meditation_icons/img-truth-meditation-.png
    - assets/meditation_icons/img-breathing-meditation-.png
    - assets/meditation_icons/img-silent-meditation-.png
    - assets/meditation_icons/1.png
    - assets/meditation_icons/2.png
    - assets/meditation_icons/3.png
    - assets/meditation_icons/4.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLt.ttf
          weight: 200
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeueMed.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueBd.ttf
          weight: 800
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
